Footer
esih-markerlab/makerlab pull request #10
Opened 2020-10-02 19:20 UTC by Chamane

2020-10-02 19:27 UTC, youko509 commented
footer

2020-10-03 15:48 UTC, youko509 requested changes

2020-10-03 15:48 UTC, youko509 commented on templates/bases/index.html
> +
ok map retire sa

2020-10-03 15:54 UTC, Chamane commented on templates/bases/index.html
> +
Ou chwazi yon font pou sit la ?

2020-10-03 15:54 UTC, Chamane commented on templates/partials/_footer.html
> +              <strong>Email:</strong> info@example.com<br>
mete adrès ayiti nou yo

2020-10-03 15:54 UTC, Chamane commented on templates/partials/_footer.html
> +        Designed by <a href="https://bootstrapmade.com/">Makerlab</a>
retire lyen sa

2020-10-03 15:55 UTC, youko509 commented on templates/bases/index.html
> +
oui pou ekriti footer

2020-10-03 16:12 UTC, youko509 approved these changes

2020-10-03 16:13 UTC, merged