add search functionality but have some issues
esih-markerlab/makerlab pull request #11
Opened 2020-10-11 01:04 UTC by youko509

li mache men sim fon recherche sam pa ekri anyen li banm tout kou ki sou li yo

2020-10-11 02:44 UTC, undisplay reviewed
Ajouter method clean lan nan form lan wap ka fe validasyon ladan'l,fe rechèch la

2020-10-11 02:50 UTC, youko509 commented
Ok mpral gad sa

2020-10-24 15:39 UTC, Chamane requested changes

2020-10-24 15:39 UTC, Chamane commented on courses/views.py
> +
Rechèch lan mache selman si mwen tape tout mo an. Sa pa enteresan. Gade [la](https://stackoverflow.com/questions/49867384/django-searchvector-using-icontains) epi korije aspè saaa

2020-10-24 15:39 UTC, Chamane commented on courses/views.py
> +
Answit rechèch la pa fèt selman sou kou yo. Fè Freedy edew sou aspè saa

2020-11-08 16:13 UTC, closed without merging